language: java
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk7

before_install:
  - secure: l6lA/6iXjx8lj1ipBVzNoIfMIoZBDhIFfrzN5EcQaEn+ECHswf5f1/ZjeRn2rRmpyqK1Em+RraFhaJ+HY0LZfDSwf1m/tLfAaV6pL/dm4W34RK40YEU2HK4KTiheyGp+eg07IaXcdGXDeQfvDzBt9rSLrt8r515S5Q6NBM25dCA+subumaqB4bntyKMrh3pd0sn1mNnnIvwldAR6TmfeoBK9Jo4EKGs3w2P8GIYF4z2PvXTDWgY2EKGOfKkUKc7sajXkytPS7WdQbT8n1n0TlqyZY5Wd0gpVAxGXnJtLG56xk/wLlIkTj06UGO+E/EsqSBQZ9yh7WQs4dEwdZjympNIuAewrwZrok1BmDMlnjOEJ0lfbsdqP5zmw6AQW8UsmkeKizFynjA9uNxxGtYCD9Rk/zxDvfax+9oKdLYjTEMIu0t617HapaZDDO8WhL6row5QHWEZ7ADuLQVaC42gEp7zTnhgpdLcOU1Dk07XIXRZFIyWT0ebcwnkIG3qtjyg08pnRdE35ht3sm3in4x9LUOcYlyVsDSEbAegv1edKAM+ESptiiP158ChQ9xn6XdxTkePbhEBAEH25e6k30BrcjL4O54p9VSsnMFWrr+tWaaG2j8BZlGbzkC3m5EdAfK3vi614bXgyvPvQjYX7/PjSU5tvWPkIYi7BGoz/3KuSzBg=
  - ls -ahl
