language: java
jdk:
  - openjdk7
before_install:
  - openssl aes-256-cbc -K $encrypted_c83b41bd1ebb_key -iv $encrypted_c83b41bd1ebb_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
  - sh prepare_environment.sh 
  - git branch -v
script:
  - ./gradlew
  - ./gradlew uploadArchives
  - ./gradlew publishPlugins || :