language: java
jdk:
  - openjdk7
before_install:
  - openssl aes-256-cbc -K $encrypted_71fd7511358b_key -iv $encrypted_71fd7511358b_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
  - sh prepare_environment.sh
script:
  - ./gradlew
  - ./gradlew uploadArchives
  - ./gradlew closeRepository publishPlugins --continue || exit 0
